# Generated by Django 3.2.5 on 2021-07-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('meta_title', models.CharField(max_length=120)),
                ('medical_name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('product_type', models.CharField(choices=[('medicine', 'Medicine'), ('devices', 'Devices'), ('hygienic_product', 'Hygienic Product')], default='medicine', max_length=20)),
                ('description', models.TextField(max_length=254)),
                ('manufacturer', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
