# Generated by Django 3.1.3 on 2021-07-07 14:21

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('meta_title', models.CharField(max_length=120, null=True)),
                ('medical_name', models.CharField(max_length=256, null=True)),
                ('slug', models.SlugField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('manufacture_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('product_type', models.CharField(choices=[('medicine', 'Medicine'), ('devices', 'Devices'), ('hygienic_product', 'Hygienic Product')], default='medicine', max_length=20)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=product.models.get_upload_path)),
                ('description', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
