# Generated by Django 3.2.5 on 2021-07-25 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('meta_title', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField()),
                ('price', models.FloatField()),
                ('appointment_date', models.CharField(max_length=50)),
                ('duration', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('packed_date', models.DateField(null=True)),
                ('blood_type', models.CharField(max_length=256)),
                ('service_type', models.CharField(choices=[('clinical microbiology', 'clinical microbiology'), ('clinical chemistry', 'clinical chemistry'), ('hematology', 'hematology'), ('blood bank', 'blood bank'), ('molecular diagnotics', 'molecular diagnotics'), ('reproductive biology', 'reproductive biology')], default='clinical microbiology', max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.CreateModel(
            name='LabAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, upload_to=service.models.get_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('lab_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.FloatField(null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='none', max_length=10)),
                ('contact', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('fixed', 'Fixed'), ('completed', 'Completed')], default='booked', max_length=20)),
                ('test_title', models.CharField(max_length=30)),
                ('appointment', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
