# Generated by Django 3.2.5 on 2021-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='appointment_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
