# Generated by Django 3.2.5 on 2021-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment',
            field=models.DateTimeField(null=True),
        ),
    ]
