# Generated by Django 3.2.5 on 2021-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_appointment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_file',
            field=models.BooleanField(default=False),
        ),
    ]
