# Generated by Django 3.2.5 on 2021-07-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_appointment_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labappointment',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='labappointment',
            name='main',
        ),
        migrations.RemoveField(
            model_name='labappointment',
            name='service',
        ),
        migrations.AddField(
            model_name='labappointment',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.appointment'),
            preserve_default=False,
        ),
    ]
