# Generated by Django 3.2.5 on 2021-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_day',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
