# Generated by Django 3.2.5 on 2021-07-24 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_auto_20210724_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('contact_number', models.IntegerField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(null=True)),
                ('payment', models.BooleanField(default=False)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('fixed', 'Fixed'), ('completed', 'Completed')], default='booked', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fixed_on', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
