# Generated by Django 3.2.5 on 2021-07-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
